runtime: ruby32
entrypoint: bundle exec ruby main.rb

env_variables:
  RUNNING_ON_SERVER: true
  BASIC_AUTH_USERNAME: "admin"
  BASIC_AUTH_PASSWORD: "islander"
  REDIS_URL: "https://abify-redis-etgmlif55a-uc.a.run.app"
  REDIS_USERNAME: "admin"
  REDIS_PASSWORD: "islander"